version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.13

    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm ci
      - run: npm run test

      - save_cache:
          paths:
            - $HOME/.npm
          key: npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}

workflows:
  version: 2
  test:
    jobs:
      - test
