version: 2
jobs:

  prepare:
    docker:
      - image: circleci/node:10.8.0

    steps:
      - checkout

      - restore_cache:
          keys:
          - npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm install

      - run: npm run ci:lock:update

      - save_cache:
          paths:
            - $HOME/.npm
          key: npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm run ci:lock:upload

  test:
    docker:
      - image: circleci/node:10.8.0

    steps:
      - checkout

      - restore_cache:
          keys:
          - npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm ci

      - run: npm run test

  automerge:
    docker:
      - image: circleci/node:10.8.0

    steps:
      - checkout
      - restore_cache:
          keys:
          - npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - run:
          name: Merge greenkeeper branch
          command: npm run ci:automerge

workflows:
  version: 2
  test:
    jobs:
      - prepare
      - test:
        requires:
          - prepare
      - automerge:
          requires:
            - test
          filters:
            branches:
              only: /greenkeeper\S*/
